server:
  port: 8081

spring:
  kafka:
    consumer:
      group-id: "default"
      bootstrap-servers: localhost:9092  # адрес и порт брокера Kafka
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kafka-db

topic:
  name: t.food.order
